### ISSUE TITLE
Vue3支持吗？

### ISSUE THREAD

**Issue by BruceAn1978** [b3241931/uniapp-wslimg#1]
UniApp中使用import方式引入组件，老是报错：
reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Uncaught ReferenceError: module is not defined
 at  (app-service.js:3252:5)
 at  (app-service.js:3408:5)
 at  (app-service.js:4990:3)

**Comment by Levi-Luo736** [comment]
解决了吗
